### ISSUE TITLE
I am keep getting lock error and multiple instance are running for a job

### ISSUE THREAD

**Issue by knoxxs** [michaelklishin/quartz-mongodb#131] opened 2016-10-13 20:50 UTC
`Error retrieving expired lock from the database. Maybe it was deleted`

Why this is happening?

I am new to quartz, pls help.

Also multiple instances are running for my job.  Though the misfire instruction is `2` :

```
quartz_qa> db.quartz_triggers.findOne({"keyName": "MessageExecutorJob___coalarts"})
{
    "_id": ObjectId("57ffc9c18f440d6d223b569b"),
    "state": "waiting",
    "calendarName": null,
    "class": "org.quartz.impl.triggers.CronTriggerImpl",
    "description": null,
    "endTime": null,
    "finalFireTime": null,
    "fireInstanceId": null,
    "jobId": ObjectId("57ffc9c18f440d6d223b5699"),
    "keyName": "MessageExecutorJob___coalarts",
    "keyGroup": "Message Executor",
    "misfireInstruction": 2,
    "nextFireTime": ISODate("2016-10-13T18:25:00Z"),
    "previousFireTime": ISODate("2016-10-13T18:24:30Z"),
    "priority": 5,
    "startTime": ISODate("2016-10-13T17:52:01Z"),
    "cronExpression": "0/30 * * * * ?",
    "timezone": "UTC"
}
```

The second instance started on misfire, I confirmed by adding a log in Misfire listener. This doesn't used to happen before while I was using RAMJobStore.

**Comment by michaelklishin** [comment] 2018-03-10 02:46
Not enough information to suggest anything specific, the issue is well over 1 year old => closing.

**Closed by michaelklishin** 2018-03-10 02:46 UTC
