### ISSUE TITLE
Maven not found version 2.1.0

### ISSUE THREAD

**Issue by BeeHuang** [michaelklishin/quartz-mongodb#159] opened 2018-03-20 09:56 UTC
https://mvnrepository.com/artifact/com.novemberain/quartz-mongodb

**Comment by michaelklishin** [comment] 2018-03-20 17:49
This project publishes artifacts [to Bintray](https://github.com/michaelklishin/quartz-mongodb#maven-artifacts).

**Comment by michaelklishin** [comment] 2018-03-20 17:49
Duplicate of #132.

**Closed by michaelklishin** 2018-03-20 17:49 UTC
